server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # CLIENTES
    location /api/clientes {
        proxy_pass http://cliente-service:5000/clientes;
    }

    # LIVROS
    location /api/livros {
        proxy_pass http://livro-service:5000/livros;
    }

    # EMPRESTIMOS
    location /api/emprestimos {
        proxy_pass http://emprestimo-service:5000/emprestimos;
    }
}